"""data table with number of side and values

Revision ID: 6841c7f2aeff
Revises: df2e12f463a4
Create Date: 2020-05-14 00:00:12.032862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6841c7f2aeff'
down_revision = 'df2e12f463a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('n', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'n')
    # ### end Alembic commands ###
