"""data table with length

Revision ID: df2e12f463a4
Revises: e43625b90eeb
Create Date: 2020-05-13 18:27:43.418344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2e12f463a4'
down_revision = 'e43625b90eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'length')
    # ### end Alembic commands ###
